apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mft-diagnostics
  namespace: nccl-test
  annotations:
    description: "MFT and RDMA diagnostics pod for Mellanox NICs"
    tags: "networking,diagnostics,mellanox,rdma"
parameters:
- name: NODE_NAME
  description: "Node name to run the diagnostics pod on"
  required: true
  # Default value (optional)
  # value: moc-r4pcc04u23-nairr
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: mft-diagnostics
    namespace: nccl-test
    labels:
      app: mft-diagnostics
      node: ${NODE_NAME}
  spec:
    nodeName: ${NODE_NAME}
    hostIPC: true
    hostNetwork: true
    hostPID: true
    containers:
    - name: mft-diagnostics
      image: nvcr.io/nvidia/pytorch:24.12-py3
      command: ["/bin/bash", "-c"]
      args:
      - |
        set -x
        echo "=========================================="
        echo "MFT and RDMA Diagnostics Pod"
        echo "Node: $(hostname)"
        echo "Target Node: ${NODE_NAME}"
        echo "=========================================="

        # ====================================================
        # Install Mellanox Firmware Tools (MFT) and RDMA Tools
        # ====================================================
        echo ""
        echo "=== Installing Mellanox Firmware Tools (MFT) and RDMA Diagnostics ==="

        # Update package list
        apt-get update -qq

        # Install dependencies and RDMA tools
        echo "Installing InfiniBand diagnostics and RDMA tools..."
        apt-get install -y -qq wget curl pciutils kmod infiniband-diags rdma-core libibverbs-dev ibverbs-utils

        # Download and install MFT from direct link
        cd /tmp

        # Use direct download link that works
        MFT_URL="https://content.mellanox.com/ofed/MLNX_OFED-24.10-1.1.4.0/MLNX_OFED_LINUX-24.10-1.1.4.0-ubuntu22.04-x86_64.tgz"
        OFED_PACKAGE="MLNX_OFED_LINUX-24.10-1.1.4.0-ubuntu22.04-x86_64.tgz"

        echo "Downloading Mellanox OFED (includes MFT)..."
        wget --timeout=60 --tries=3 -O ${OFED_PACKAGE} ${MFT_URL} || {
          echo "OFED download failed, trying MFT-only package..."

          # Try MFT-only from web.archive.org or github mirror
          MFT_VERSION="4.28.0-83"
          MFT_PACKAGE="mft-${MFT_VERSION}-x86_64-deb.tgz"

          wget --timeout=60 --tries=2 -O ${MFT_PACKAGE} \
            "http://www.mellanox.com/downloads/MFT/mft-${MFT_VERSION}-x86_64-deb.tgz" || \
          echo "All downloads failed, trying to use existing OFED..."
        }

        # Check if we got OFED package
        if [ -f "${OFED_PACKAGE}" ] && file ${OFED_PACKAGE} | grep -q "gzip compressed"; then
          echo "Extracting OFED package..."
          tar xzf ${OFED_PACKAGE}
          OFED_DIR=$(ls -d MLNX_OFED_LINUX-* | head -1)

          if [ -d "${OFED_DIR}" ]; then
            # Extract just MFT from OFED
            if [ -f "${OFED_DIR}/DEBS/mft_"*.deb ]; then
              echo "Installing MFT from OFED..."
              dpkg -i ${OFED_DIR}/DEBS/mft_*.deb || echo "MFT dpkg install had warnings"
              dpkg -i ${OFED_DIR}/DEBS/kernel-mft-dkms_*.deb 2>/dev/null || echo "DKMS not needed"
            fi
          fi
        elif [ -f "mft-*.tgz" ] && file mft-*.tgz | grep -q "gzip compressed"; then
          echo "Extracting MFT package..."
          tar xzf mft-*.tgz
          cd mft-*-x86_64-deb 2>/dev/null || cd mft-*/

          if [ -f "./install.sh" ]; then
            echo "Installing MFT..."
            ./install.sh --without-dkms
          fi
        fi

        # Try to start MFT
        echo "Starting MFT service..."
        if [ -f /etc/init.d/mst ]; then
          /etc/init.d/mst start
          MFT_STATUS="✓ MFT installed and started"
        elif command -v mst >/dev/null 2>&1; then
          mst start
          MFT_STATUS="✓ MFT installed and started"
        else
          MFT_STATUS="✗ MFT not installed (downloads may have failed)"
        fi

        echo "${MFT_STATUS}"

        # Verify installations and set PATH
        echo ""
        echo "=== Verifying Tool Availability ==="

        # Find where tools were installed
        MST_PATH=$(find /usr -name mst -type f 2>/dev/null | grep -E "bin/mst$" | head -1)
        if [ -n "${MST_PATH}" ]; then
          MST_DIR=$(dirname ${MST_PATH})
          export PATH=${MST_DIR}:$PATH
          echo "✓ MFT tools found in: ${MST_DIR}"
        fi

        # Check each tool
        command -v mst >/dev/null 2>&1 && echo "✓ mst found: $(which mst)" || echo "✗ mst not found"
        command -v mlxconfig >/dev/null 2>&1 && echo "✓ mlxconfig found: $(which mlxconfig)" || echo "✗ mlxconfig not found"
        command -v ibdev2netdev >/dev/null 2>&1 && echo "✓ ibdev2netdev found: $(which ibdev2netdev)" || echo "✗ ibdev2netdev not found"
        command -v ibstat >/dev/null 2>&1 && echo "✓ ibstat found: $(which ibstat)" || echo "✗ ibstat not found"

        # Add to bashrc for interactive sessions
        if [ -n "${MST_DIR}" ]; then
          echo "export PATH=${MST_DIR}:\$PATH" >> /root/.bashrc
        fi

        # ====================================================
        # Display System Information
        # ====================================================
        echo ""
        echo "=========================================="
        echo "System Information"
        echo "=========================================="
        echo "Hostname: $(hostname)"
        echo "Kernel: $(uname -r)"
        echo "Date: $(date)"

        # ====================================================
        # Display Mellanox NIC and RDMA Information
        # ====================================================
        echo ""
        echo "=========================================="
        echo "Mellanox NIC Information"
        echo "=========================================="

        # List PCI Mellanox devices
        echo ""
        echo "=== Mellanox PCI Devices ==="
        lspci | grep -i mellanox || echo "No Mellanox devices found via lspci"

        # List MST devices
        echo ""
        echo "=== MST Devices ==="
        if command -v mst &> /dev/null; then
          mst status -v || echo "Could not get MST status"
        else
          echo "✗ mst command not available"
        fi

        # ====================================================
        # RDMA/InfiniBand Information
        # ====================================================
        echo ""
        echo "=========================================="
        echo "RDMA/InfiniBand Information"
        echo "=========================================="

        # IB device to network mapping
        echo ""
        echo "=== IB Device to Network Interface Mapping ==="
        if command -v ibdev2netdev &> /dev/null; then
          ibdev2netdev || echo "Could not run ibdev2netdev"
        else
          echo "✗ ibdev2netdev not available"
        fi

        # RDMA devices list
        echo ""
        echo "=== RDMA Devices ==="
        if command -v ibv_devinfo &> /dev/null; then
          ibv_devinfo -l || echo "No RDMA devices found"
        else
          echo "✗ ibv_devinfo not available"
        fi

        # IB port status
        echo ""
        echo "=== IB Port Status ==="
        if command -v ibstat &> /dev/null; then
          ibstat || echo "Could not get IB status"
        else
          echo "✗ ibstat not available"
        fi

        # InfiniBand devices from /dev
        echo ""
        echo "=== InfiniBand Devices in /dev ==="
        ls -la /dev/infiniband/ 2>/dev/null || echo "No /dev/infiniband directory"

        # RDMA devices from /sys
        echo ""
        echo "=== RDMA Devices in /sys ==="
        ls -la /sys/class/infiniband/ 2>/dev/null || echo "No /sys/class/infiniband directory"

        # Network interfaces
        echo ""
        echo "=== Network Interfaces (Mellanox) ==="
        for iface in $(ls /sys/class/net/); do
          driver=$(readlink /sys/class/net/$iface/device/driver 2>/dev/null | xargs basename 2>/dev/null)
          if [ "$driver" = "mlx5_core" ]; then
            addr=$(cat /sys/class/net/$iface/address 2>/dev/null)
            mtu=$(cat /sys/class/net/$iface/mtu 2>/dev/null)
            state=$(cat /sys/class/net/$iface/operstate 2>/dev/null)
            speed=$(cat /sys/class/net/$iface/speed 2>/dev/null || echo "unknown")
            echo "  $iface: $addr (state: $state, speed: ${speed}Mb/s, mtu: $mtu)"
          fi
        done

        # ====================================================
        # Available Commands Summary
        # ====================================================
        echo ""
        echo "=========================================="
        echo "Available Diagnostic Tools"
        echo "=========================================="
        echo ""
        echo "MFT (Mellanox Firmware Tools):"
        echo "  mst status                      - Show MST devices"
        echo "  mlxconfig -d <dev> q            - Query firmware settings"
        echo "  mlxconfig -d <dev> set          - Change firmware settings"
        echo "  mstflint -d <dev> q             - Query firmware version"
        echo ""
        echo "RDMA/InfiniBand Diagnostics:"
        echo "  ibstat                          - Show IB port status and state"
        echo "  ibv_devinfo                     - Show detailed RDMA device info"
        echo "  ibv_devinfo -v                  - Verbose RDMA device info"
        echo "  ibv_devices                     - List RDMA devices"
        echo "  perfquery                       - Query IB performance counters"
        echo ""
        echo "Note: ibdev2netdev may not be available. Use these alternatives:"
        echo "  Alternative 1 - List RDMA devices and network interfaces separately:"
        echo "    ibv_devices                   - List RDMA devices (mlx5_6, mlx5_7, etc.)"
        echo "    ip link show | grep mlx       - Show network interfaces"
        echo "    ls -la /sys/class/net/        - List all network interfaces"
        echo ""
        echo "  Alternative 2 - Manual mapping:"
        echo "    cat /sys/class/net/*/device/infiniband/*/node_desc"
        echo "    for iface in \$(ls /sys/class/net/); do"
        echo "      [ -d /sys/class/net/\$iface/device/infiniband ] && \\"
        echo "      echo \"\$iface: \$(ls /sys/class/net/\$iface/device/infiniband/)\""
        echo "    done"
        echo ""
        echo "Example Usage:"
        echo "  # Access the pod"
        echo "  oc exec -it mft-diagnostics -n nccl-test -- bash"
        echo ""
        echo "  # Check MST devices"
        echo "  mst status"
        echo ""
        echo "  # Query NIC firmware (use PCI address from mst status)"
        echo "  mlxconfig -d 03:00.0 query"
        echo "  mlxconfig -d 03:00.0 query | grep NUM_OF_VFS"
        echo ""
        echo "  # Check RDMA devices and status"
        echo "  ibv_devices"
        echo "  ibv_devinfo mlx5_6"
        echo "  ibstat"
        echo ""
        echo "  # Map RDMA devices to network interfaces"
        echo "  for dev in /sys/class/infiniband/*; do"
        echo "    dev_name=\$(basename \$dev)"
        echo "    port_state=\$(cat \$dev/ports/1/state 2>/dev/null || echo 'N/A')"
        echo "    netdev=\$(ls \$dev/device/net/ 2>/dev/null)"
        echo "    echo \"\$dev_name => \$netdev (port state: \$port_state)\""
        echo "  done"
        echo ""
        echo "=========================================="
        echo "Pod Ready - Container will remain running"
        echo "=========================================="

        # Keep container running for interactive access
        sleep infinity

      env:
      - name: NODE_NAME
        value: ${NODE_NAME}

      resources:
        requests:
          cpu: "2"
          memory: "4Gi"
        limits:
          cpu: "4"
          memory: "8Gi"

      volumeMounts:
      - name: dev
        mountPath: /dev
      - name: sys
        mountPath: /sys

      securityContext:
        privileged: true
        capabilities:
          add:
          - SYS_ADMIN
          - SYS_RAWIO
          - NET_ADMIN

    volumes:
    - name: dev
      hostPath:
        path: /dev
    - name: sys
      hostPath:
        path: /sys

    restartPolicy: Always
